### ISSUE TITLE
Crashes when pipelines use list syntax for environment variables

### ISSUE THREAD

**Issue by azz** [seek-oss/buildkite-signed-pipeline#35]
Pipelines can list env vars as lists, similar to docker-compose.

```yaml
steps:
  - command: true
    env:
      - MY_VAR=value
```

This causes the pipeline signing to fail because it expects a map:

https://github.com/seek-oss/buildkite-signed-pipeline/blob/b598adbed132529869ed0f1167a0c524f697c8bd/cmd/buildkite-signed-pipeline/signer.go#L134-L140

```

panic: reflect: call of reflect.Value.MapKeys on slice Value
--
  |  
  | goroutine 1 [running]:
  | reflect.flag.mustBe(0x97, 0x15)
  | /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:207 +0xb4
  | reflect.Value.MapKeys(0x850340, 0xc00049c220, 0x97, 0x3, 0xc0002fa528, 0x1)
  | /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:1133 +0x49
  | main.SharedSecretSigner.signStep(0xc00046c080, 0x20, 0x0, 0x0, 0x876e60, 0xc00049c250, 0x194, 0x1, 0xc0001ae600, 0x0, ...)
  | /Users/zsims/projects/buildkite-signed-pipeline/signer.go:137 +0x50e
  | main.SharedSecretSigner.Sign(0xc00046c080, 0x20, 0x0, 0x0, 0x878960, 0xc0001ae0f0, 0x7f742a184000, 0x0, 0xc000066ba0, 0x0)
  | /Users/zsims/projects/buildkite-signed-pipeline/signer.go:57 +0x668
  | main.(*uploadCommand).run(0xc00000ae40, 0xc00016bc20, 0x859000, 0xc000035450)
  | /Users/zsims/projects/buildkite-signed-pipeline/main.go:100 +0xfa
  | main.(*uploadCommand).run-fm(0xc00016bc20, 0x409af3, 0x88d720)
  | /Users/zsims/projects/buildkite-signed-pipeline/main.go:38 +0x34
  | gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc0000c20d8, 0xc00016bc20, 0x0, 0x0)
  | /Users/zsims/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
  | gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc0000c4690, 0xc00016bc20, 0x0, 0x0)
  | /Users/zsims/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdf
  | gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc0000c4690, 0xc00016bc20, 0xc000035440, 0x1, 0x1, 0x0, 0x0, 0xc00016e960, 0x0)
  | /Users/zsims/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x8f
  | gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc0000c4690, 0xc00001c090, 0x3, 0x3, 0x1, 0xc00000c1e8, 0x0, 0x1)
  | /Users/zsims/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x1fa
  | main.main()
  | /Users/zsims/projects/buildkite-signed-pipeline/main.go:80 +0xa6a


```

**Comment by zsims** [comment]
Thanks for raising this and the detailed report. Will fix this asap.

**Comment by zsims** [comment]
Fixed version: https://github.com/seek-oss/buildkite-signed-pipeline/releases/tag/v1.8.0
Let me know how you go

**Comment by azz** [comment]
Confirmed working. Thanks for the quick turn-around!

**Comment by zsims** [comment]
Awesome, thanks :D!
